modLoader="javafml"
loaderVersion="[36,)"
license="ARR"
issueTrackerURL="https://example.invalid/"
#logoFile="logo.png"

[[mods]]
modId="enchant_icon"
version="${version}"
displayName="Enchant Icon"
displayURL="https://example.com"
description="[ACCESS DENIED]"
authors="YuriCat, 水蓝冰青"
credits="Violet Modding, for their multi-loader project architecture used in Botania"

[[dependencies.enchant_icon]]
modId="minecraft"
mandatory=true
versionRange="[1.16,1.17)"
# 32.0.72 is the earliest version on 1.16.x that introduces bundled SpongePowered Mixin.
# Note that Forge does not exists on 1.16, only 1.16.1.
# For 1.15.x, 31.2.45 introduces the backport of the said change above.
[[dependencies.enchant_icon]]
modId="forge"
mandatory=true
versionRange="[32.0.72,)"
