modLoader="javafml"
loaderVersion="[1,)"
license="ARR"
issueTrackerURL="https://example.invalid/"
#logoFile="logo.png"
# NeoForge plan to remove this in the future; need to test whether it will silently ignore this line
displayTest="IGNORE_ALL_VERSION"

[[mods]]
modId="enchant_icon"
version="${file.jarVersion}"
displayName="Enchant Icon"
displayURL="https://example.com"
description="[ACCESS DENIED]"
authors="YuriCat, 水蓝冰青"
credits="Violet Modding, for their multi-loader project architecture used in Botania"

[[mixins]]
config='enchant_icon.mixins.json'

[[dependencies.enchant_icon]]
modId="minecraft"
mandatory=true
versionRange="[1.20.5,1.21)"