modLoader="javafml"
loaderVersion="[40,)"
license="ARR"
issueTrackerURL="https://example.invalid/"
#logoFile="logo.png"
# This mod has no server component; thus we declare "ignore all version" here,
# so that we don't cause that infamous "red X" to appear.
# See https://github.com/MinecraftForge/MinecraftForge/pull/8656 for more details.
displayTest="IGNORE_ALL_VERSION"

[[mods]]
modId="enchant_icon"
version="${file.jarVersion}"
displayName="Enchant Icon"
displayURL="https://example.com"
description="[ACCESS DENIED]"
authors="YuriCat, 水蓝冰青"
credits="Violet Modding, for their multi-loader project architecture used in Botania"

[[dependencies.enchant_icon]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3]"