name: Test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Config Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            16
            17
            21
      - name: Apply Cache
        uses: actions/cache@v4
        if: always()
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: $${{ runner.os }}-gradle
      - name: Test 1.20.6 Build
        id: test-build-1-20-6
        run: ./gradlew :1.20.6-fabric:build :1.20.6-forge:build :1.20.6-neoforge:build
      - name: Test 1.20.2 Build
        id: test-build-1-20-2
        run: ./gradlew :1.20.2-neoforge:build
      - name: Test 1.20.1 Build
        id: test-build-1-20-1
        run: ./gradlew :1.20.1-fabric:build :1.20.1-forge:build :1.20.1-quilt:build
      - name: Test 1.19.4 Build
        id: test-build-1-19-4
        run: ./gradlew :1.19.4-fabric:build :1.19.4-forge:build :1.19.4-quilt:build
      - name: Test 1.19.3 Build
        id: test-build-1-19-3
        run: ./gradlew :1.19.3-fabric:build :1.19.3-forge:build :1.19.3-quilt:build
      - name: Test 1.19-2 Build
        id: test-build-1-19-2
        run: ./gradlew :1.19.2-fabric:build :1.19.2-forge:build :1.19.2-quilt:build
      - name: Test 1.18 Build
        id: test-build-1-18
        run: ./gradlew :1.18.2-fabric:build :1.18.2-forge:build :1.18.2-quilt:build
      - name: Test 1.17 Build
        id: test-build-1-17
        run: ./gradlew :1.17.1-fabric:build :1.17.1-forge:build
      - name: Test 1.16 Build
        id: test-build-1-16
        run: ./gradlew :1.16.5-fabric:build :1.16.5-forge:build
